sonar.projectKey=user-service-key
sonar.organization=innowise-courses-organization

sonar.sources=src/main/java
sonar.tests=src/test/java

sonar.java.binaries=target/classes

sonar.sourceEncoding=UTF-8