spring:
  datasource:
    url: jdbc:postgresql://userservice-db:5432/${USERSERVICE_POSTGRES_DB}

  data:
    redis:
      host: userservice-cache
      port: 6379

grpc:
  client:
    userClientService:
      address: authservice:${GRPC_AUTHSERVICE_PORT}
      negotiation-type: PLAINTEXT