spring.application.name=user-service

spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.data.redis.host=localhost
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.timeout=2000ms

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/changelog-master.yml

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate