spring:
  datasource:
    hikari:
      connection-timeout: 2000
      max-lifetime: 30000
  data:
    redis:
      timeout: 2000ms
      lettuce:
        shutdown-timeout: 100ms
  cache:
    type: none

service:
  secret: b0f9e70f427eb0e6e942268b065afe24928ff74acade37458c7f3994d6999f9b

jwt:
  secret: test-secret-key-test-secret-key-test-secret-key