spring:
  datasource:
    url: jdbc:postgresql://localhost:${USERSERVICE_POSTGRES_PORT}/${USERSERVICE_POSTGRES_DB}

  data:
    redis:
      host: localhost

grpc:
  client:
    userClientService:
      address: localhost:${GRPC_AUTHSERVICE_PORT}
      negotiation-type: PLAINTEXT