server:
  port: 8080

spring:
  application:
    name: user-service

  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      port: ${REDIS_PORT}
      timeout: 2000ms

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yml

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

jwt:
  secret: ${JWT_SECRET_KEY}