spring:
  datasource:
    hikari:
      connection-timeout: 2000
      max-lifetime: 30000
  data:
    redis:
      timeout: 2000ms
      lettuce:
        shutdown-timeout: 100ms
  cache:
    type: none

jwt:
  secret: test-secret-key-test-secret-key-test-secret-key